/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.maksimenkov.stack;

public class Stack {
  int[] arr = new int[100500];
  int last = 0;
  int stack_max_idx = 100499;
  public void push(int x){
    if (last < stack_max_idx){
      last++;
      arr[last] = x;
    }
    else {
      System.out.println("Stack overflow!");
    }
  }
  public int pop(){
    if (last > 0){
      int x = arr[last];
      last--;
      return x;
    }
    else {
      System.out.println("Stack is empty!");
      return -1000000;
    }
  }
  public int count(){
    return last;
  }

  public void pushStack(Stack stack){
    while (stack.count() != 0) {
      int x = stack.pop();
      push(x);
      if (last == 100499){
        push(0);
        break;
      }
    }
  }
  public Stack popStack(int x){
    Stack stack = new Stack();
    for (int i = 0; i < x; i++) {
      stack.push(pop());
      if (last == 0){
        return stack;
      }
    }
    return stack;
  }
}
